### ISSUE TITLE
Error with pear/tar requirement

### ISSUE THREAD

**Issue by arkin-** [wapmorgan/UnifiedArchive#1]
Hi,

Your package looks great, I'm just running into problems installing...

I have no use for tar or do I use pear, I plan to use zip + rar, could you please remove this package from the requirements.

> wapmorgan/unified-archive dev-master requires pear/archive_tar dev-master -> no matching package found.

Submitted pull request #2

**Comment by wapmorgan** [comment]
May be there is a packagist temporary trouble? pear/tar is [available](https://packagist.org/packages/pear/archive_tar).
Right, this package is not critical, but very recommended.

**Comment by arkin-** [comment]
If its not a requirement, can we remove it from the required dependencies and put it in the suggested instead?

**Comment by wapmorgan** [comment]
Fixed in #2
