### ISSUE TITLE
extract tar.bz2, tar.xz, open function return NULL

### ISSUE THREAD

**Issue by huyouheng** [wapmorgan/UnifiedArchive#13]
**extract tar.bg2 and  tar.xz error.**

`Call to a member function extractFiles() on null`

 - OS: ubuntu16.04
 - Version of library: 0.1.0
 - PHP Version: 7.2.5

> try {
              $archive = UnifiedArchive::open('/home/hi/a.tar.bz2');
              $result = $archive->extractFiles('/home/hi/a');
        } catch (\Exception $e) {
                  info($e->getMessage());
        }

**Comment by wapmorgan** [comment]
Get output of `./vendor/bin/cam -f` in terminal and attach.
Probably you need to install extra php-extensions to work with this formats.
