### ISSUE TITLE
UnifiedArchive::open() returns null for .tar.Z files.

### ISSUE THREAD

**Issue by jasonhoule** [wapmorgan/UnifiedArchive#15]
**Describe the bug**
When attempting to open a .tar.z file null is returned.

**Configration (please complete the following information):**
 - OS: [e.g. linux / windows / osx] Linux
 - Version of library: [e.g. 0.1.0] 0.1.2

**To Reproduce**
Steps to reproduce the behavior (your code).
Attempt to open a LZW compressed tar file.

**Expected behavior**
Expected a UnifiedArchive instance to be returned.

I have submitted pull request: Fix check for LZW compression #14

**Comment by wapmorgan** [comment]
Merged, check it again.

**Comment by wapmorgan** [comment]
Is it still problem?

**Comment by jasonhoule** [comment]
It is working great now. Thank you!
