### ISSUE TITLE
rar error massage problem

### ISSUE THREAD

**Issue by jackzp** [wapmorgan/UnifiedArchive#16]
There is one file shows error like this

An uncaught Exception was encountered
Type: RarException

Message: unRAR internal error: Failed to open /var/www/sub/2020/01/157838650259114.rar: ERAR_BAD_ARCHIVE

Filename: /var/www/vendor/wapmorgan/unified-archive/src/Formats/Rar.php

Line Number: 34

Backtrace:

File: /var/www/vendor/wapmorgan/unified-archive/src/Formats/Rar.php
Line: 34
Function: open

File: /var/www/vendor/wapmorgan/unified-archive/src/Formats/Rar.php
Line: 24
Function: open

File: /var/www/vendor/wapmorgan/unified-archive/src/UnifiedArchive.php
Line: 257
Function: __construct

File: /var/www/vendor/wapmorgan/unified-archive/src/UnifiedArchive.php
Line: 106
Function: __construct

AND i try everthing to avoid the error , it still there .. i saw the doc said if there is mistake it will return null .. but it's not ..

**Comment by wapmorgan** [comment]
Looks like an archive is corrupted.

**Comment by jackzp** [comment]
my purpose is allow user to upload files , and show them what's in the file , so if file is corrupted , and there is an error there , what's my option ?

 i try 

@$archive = \wapmorgan\UnifiedArchive\UnifiedArchive::open($sub_file); 
if($archive = \wapmorgan\UnifiedArchive\UnifiedArchive::open($sub_file))

error still there 

thanks

**Comment by wapmorgan** [comment]
You can wrap it within `try...catch` block

**Comment by jackzp** [comment]
got it thanks !
