### ISSUE TITLE
Returns null on rar archives

### ISSUE THREAD

**Issue by OnArs** [wapmorgan/UnifiedArchive#20]
**Describe the bug**
Seems like UnifiedArchive can't recognize rar archives when everything is ok with zip ones.

**Configration (please complete the following information):**
 - MacOS: 10.14.6
 - PHP: 7.4.1
 - Laravel Framework: 5.7.28
 - Version of library: 0.2.0

**To Reproduce**
1. Download this rar archive [ftp://emexonline.com/megaprice/24H.rar](ftp://emexonline.com/megaprice/24H.rar)
2. `$archive = UnifiedArchive::open("24H.rar");`
3. null

**Expected behavior**

**Comment by wapmorgan** [comment]
Have you installed `ext-rar` as described in [Formats section](https://github.com/wapmorgan/UnifiedArchive#formats-support) ?

**Comment by OnArs** [comment]
No, I've tried using pecl or manually but with no luck. I decided to use command line rar with php exec instead

**Comment by wapmorgan** [comment]
`pecl install rar` should make it work
