### ISSUE TITLE
Work with 7zip archive format

### ISSUE THREAD

**Issue by AnriKoVa** [wapmorgan/UnifiedArchive#21]
Hi, thanks for very nice, useful package.
I try to implement creating achives  .7z and .7zip from files, add this extentions too - gemorroj/archive7z, but get the next error:

`Could not create archive: Binary of 7-zip is not available`

I saw in you docs that need use "Uses system binary 7z to work". I try convert files that need archive to binary but this not help, not good understand how it use.
Can a bit clarify where I made a mistake, or some example how to work with create .7z and .7zip archive?
Thank a lot.

**Comment by wapmorgan** [comment]
[readme of Gemorroj/Archive7z](https://github.com/Gemorroj/Archive7z#requirements) says:

> PHP >= 7.1.3
> shell
> 7-zip >= 7.30 (p7zip >= 9.38)
> 
So you need to install 7-zip package in your OS
