### ISSUE TITLE
Unable to extract a ".tar.xz" archive

### ISSUE THREAD

**Issue by Tantrisse** [wapmorgan/UnifiedArchive#27]
**Describe the bug**
When trying to open a `tar.xz`, the `open` function return `null`.

**Configration (please complete the following information):**
 - OS: linux
 - Version of library: latest, PHP 8

**To Reproduce**
What I've done :
- `composer require wapmorgan/unified-archive`
- `composer require pear/archive_tar`
- Installed `xz` extension https://github.com/codemasher/php-ext-xz via :

```
RUN mkdir -p /tmp/php-ext-xz \
    && git clone https://github.com/codemasher/php-ext-xz.git /tmp/php-ext-xz \
    && docker-php-ext-configure /tmp/php-ext-xz \
    && docker-php-ext-install /tmp/php-ext-xz \
    && rm -r /tmp/php-ext-xz
```

I'm working inside a docker container but the installation is OK, there is a `xz` extension loaded.

My problem is when doing `$archive = UnifiedArchive::open('archive.tar.xz');` the format found by UnifiedArchive is `TAR_LZMA` which require `extension_loaded('lzma2')` to be true in `TarByPear.php`.

I don't have this extension and can't find anything on Google on how to install it for 1 hour now...

What I find strange is, if I manually change the `extension_loaded('lzma2')` to `extension_loaded('xz')` in `TarByPear.php` line 71, the archive is correctly opened and I can use `$archive->extractFiles('/tmp/');` without problem, the archive is decompressed and extracted...

What I my missing, I'm going mad ! ^^

I should add, I tried to change the extension of my archive to 
- `.tar` -> exception (`UnexpectedValueException` `TarByPhar` line 94)
- `.xz` -> memory exhaustion (it seems it try to load the whole archive in memory)

Hope it's a simple mistake on my end ! Help !

**Comment by wapmorgan** [comment]
Firstly, thanks for so big explanation.
Secondly, yes, it's a mistake in `extension_loaded()` call.
I will update it in 1 hour

**Comment by Tantrisse** [comment]
Hi, thanks for the update, I wasn't _that_ mad after all ^^

I'm waiting for the update on Packagist, in the meantime I updated the code manually and can continue working, all's good !

Thank you.

**Comment by Tantrisse** [comment]
Last update, version 1.1.2 fixed the issue and is now on packagist. Thx.
