### ISSUE TITLE
Creating a tar.gz file also creates a .tar file

### ISSUE THREAD

**Issue by dbpolito** [wapmorgan/UnifiedArchive#28]
**Describe the bug**

I'm creating a `tar.gz` file with something like:

```php
UnifiedArchive::archiveDirectory($path, 'file.tar.gz');
```

The result is 2 files gets created: `file.tar` and `file.tar.gz`.

I'm manually deleting `.tar` on my implementation but wanted to check if there is any reason for keeping it, I can open a PR to fix this behavior, just wanted to check first.

**Comment by wapmorgan** [comment]
That's due to `TarByPhar` driver and `phar` process of archive creation.
Will be fixed in next release.

**Comment by wapmorgan** [comment]
Give output of two commands:
- `./vendor/bin/cam -f`
- `./vendor/bin/cam -D`

**Comment by wapmorgan** [comment]
Check out `dev-master` version, it updated in 513397f71b1ff1db2793cdfd88112f7d64e2c9e7

**Comment by wapmorgan** [comment]
Check out `dev-master` version, it updated in 513397f71b1ff1db2793cdfd88112f7d64e2c9e7

**Comment by wapmorgan** [comment]
@dbpolito please check out `dev-master`. It should be fixed

**Comment by wapmorgan** [comment]
Should be closed in last releases
