### ISSUE TITLE
open($fileName, password: given) broken

### ISSUE THREAD

**Issue by rotdrop** [wapmorgan/UnifiedArchive#37]
The square-brackets at the RHS must vanish:

https://github.com/wapmorgan/UnifiedArchive/blob/876ab148b4a56e266266bec506301fa1263e0c0d/src/UnifiedArchive.php#L83

Otherwise just specifying a password will lead to "array to string conversion" errors. Of course, the work-around is to specify options explicitly. I think this would be a good candidate for a hot-fix release.

Thx for this package!

**Comment by wapmorgan** [comment]
Still in WIP 1.1.8 version.
Will add, thx for feedback!

**Comment by rotdrop** [comment]
I think this is already fixed on the master branch by commit ccf027205d7c4ea658ef8b8442287101504969af

**Comment by wapmorgan** [comment]
released in 1.1.8.
