### ISSUE TITLE
NelexaZip driver returns DateTimeImmutable as modificationTime

### ISSUE THREAD

**Issue by rotdrop** [wapmorgan/UnifiedArchive#38]
https://github.com/wapmorgan/UnifiedArchive/blob/495bf423526aac444f0432b0853abeca3fe9b9e2/src/Drivers/NelexaZip.php#L140

Here is missing a `$info->getMTime()->getTimestamp()`.

At least in the API doc it is stated that the mtime is a Unix time-stamp.

**Comment by wapmorgan** [comment]
released in 1.1.8.
