### ISSUE TITLE
getComment() throws but should return null instead

### ISSUE THREAD

**Issue by rotdrop** [wapmorgan/UnifiedArchive#39]
**Describe the bug**

API documents that UnifiedArchive::getComment() should return `null` when comments are not supported by either the archiver format or the used driver:

https://github.com/wapmorgan/UnifiedArchive/blob/master/docs/API.md#archive-information

However, the method actually throws an `UnsupportedOperationException`, see

https://github.com/wapmorgan/UnifiedArchive/blob/495bf423526aac444f0432b0853abeca3fe9b9e2/src/Drivers/BasicDriver.php#L260

**Configration (please complete the following information):**
Irrelevant for this issue.

**To Reproduce**
Run `UnifiedArchive::getComment()` e.g. on a `.tar` file.

**Expected behavior**
The method should return `null` as per API documentation or the API documentation should state the the method throws. It is of course perfectly fine if the method throws an exception, it is just documented differently.

**Comment by wapmorgan** [comment]
Fixed in 0d8a9b8ea67934f9ee5e018dbea1d9997e6d0896

**Comment by wapmorgan** [comment]
released in 1.1.8.
