### ISSUE TITLE
getResource method

### ISSUE THREAD

**Issue by flip111** [wapmorgan/UnifiedArchive#4]
Would it be possible to add a method to get the raw resource? My use case is that i have a bunch of text file in a zip file. I didn't inspect the code of this package but i assume it's using functions like https://secure.php.net/manual/en/function.zip-open.php which give back a resource. Then the resource can be used to pass to `file()` yes file also takes streams and such. So then i can split my text files into an array of lines. Right now i think the best option would be to use `getFileContents` (from the API) and then `preg_split('/\R/', $str);`. But working on resources is just nice for a bunch of things so might be worthwhile adding a method to get the resource, and possibly a method to get the file as an array of lines.

**Comment by wapmorgan** [comment]
There is no need to open access to underlying resources in API, so you can extract all files and then open them as you want.

**Comment by flip111** [comment]
why do extra work to extract all files when just one is needed ?

**Comment by wapmorgan** [comment]
Because splitting text files into array of lines is just one case, and create another method in API to access file stream is overhead for api. I'll think about this, but for now this opportunity is not necessary.
If server configuration allow you read all file in memory, then why use streams? Just for fgets()?
If file is too big, just unpack it on storage and work like with normal file.

**Comment by flip111** [comment]
I was just suggesting this method to avoid overhead. What you propose does this:

1. read archive from disk
2. write unpacked archive to RAM (this is part of unpacking)
3. write file to disk
4. open file pointer to file (in case of using streams)
5. write split lines to RAM (php strings)
6. remove file from disk

If you can use streams then you can go directly from RAM to RAM (step 2 to step 5) and you can skip step 3 and step 6. This should be a lot faster (also depending on what kind of disk you use).

The `getResource` method won't be called in other use cases, so the overhead you mention is only when parsing the PHP file to generate opcodes. If you have opcache on then this overhead is gone. You still need a few bytes in RAM to register a new method.

**Comment by wapmorgan** [comment]
If other people agree that this useful method, I will add it.

**Comment by wapmorgan** [comment]
So, anybody else thinks it's a good addition?

**Comment by flip111** [comment]
Please don't implement it just for me, it's not worth to do it for 1 person.

**Comment by wapmorgan** [comment]
Ok, may be in future I will rethink this, but now it's closed.

**Comment by wapmorgan** [comment]
I've added `getFileResource()` in **0.2** branch that will be released soon. Now it supports native streams only for zip and rear archives, all other types simulate streaming.
