### ISSUE TITLE
mime_content_type($fileName) cannot work because of strtolower($fileName)

### ISSUE THREAD

**Issue by rotdrop** [wapmorgan/UnifiedArchive#40]
Hi there,

this line:

https://github.com/wapmorgan/UnifiedArchive/blob/4a3a29d939a4520344e3405fa9ab8c77ae1b4143/src/Formats.php#L131

makes the mime_content_check($fileName) fail at this point:

https://github.com/wapmorgan/UnifiedArchive/blob/4a3a29d939a4520344e3405fa9ab8c77ae1b4143/src/Formats.php#L151

At least when used with file-systems which are case sensitive.

**Comment by wapmorgan** [comment]
[1.1.9](https://github.com/wapmorgan/UnifiedArchive/releases/tag/1.1.9)
