### ISSUE TITLE
what if i don't want to use pear ?

### ISSUE THREAD

**Issue by abolabo** [wapmorgan/UnifiedArchive#5]
Hi.
Your code is awesome!

I tried to unpack tar.gz archive but i have no pear library installed. And i do not plan use it in the future. 
I suggest you unpack tar.gz with PharData php-class instead. It can to extract tar archives too.
```
try {
          $phar = new PharData($archive_filename);
          $phar->extractTo($dest_directory, null, true);
} catch (Exception $e) {}

```
See this check
https://github.com/wapmorgan/UnifiedArchive/blob/a51121f88ec7a6f699e499b2c0cae1db03d2c37e/src/UnifiedArchive.php#L60

**Comment by wapmorgan** [comment]
Oh, it requires some time to rewrite all code related to tar-archives, by the way PharData does not support tar.xz and tar.Z formats.

**Comment by alabama** [comment]
@abolabo had the same problem.
PEAR has ported some modules to packagist. Archive_Tar is one of them: https://packagist.org/packages/pear/archive_tar

In the composer suggest section it is also suggested to install so just 
`composer require pear/archive_tar`

**Comment by wapmorgan** [comment]
I've added ext-phar support in **dev-master**. You can test it.

**Comment by wapmorgan** [comment]
@abolabo test, pls

**Comment by wapmorgan** [comment]
@abolabo ping

**Comment by abolabo** [comment]
thank you. i'll test a bit later and let you know)

**Comment by wapmorgan** [comment]
Mark this as closed.
