### ISSUE TITLE
Extract Not Working

### ISSUE THREAD

**Issue by jasontll** [wapmorgan/UnifiedArchive#7]
I was trying to extract TAR files and the UnifiedArchive have no problem opening the file, but the extract method always returned false. Is there any way I can debug the issue? 

I have tried both with and without installing the Archive_Tar package.

**Comment by wapmorgan** [comment]
Sorry for that. Fixed in **dev-master**. Please, check on your side.

**Comment by jasontll** [comment]
Thank you! The update worked and I am closing this issue.
