### ISSUE TITLE
Not working in php 5.6

### ISSUE THREAD

**Issue by disiri** [wapmorgan/UnifiedArchive#9]
Hi,

I tried to use the package in system running on php 5.6 but got the below error.
Static function wapmorgan\UnifiedArchive\AbstractArchive::open() should not be abstract

UnifiedArchive::open($image_path)

Do you have any idea?

**Comment by wapmorgan** [comment]
Hello. I've changed AbstarctArchive and made these functions non-abstract. Check it out.

**Comment by wapmorgan** [comment]
Pls, check out **dev-master** branch.

**Comment by wapmorgan** [comment]
@disiri So what?

**Comment by wapmorgan** [comment]
@disiri I need your answer. Can you test it again?

**Comment by disiri** [comment]
Hi wapmorgan,

Sorry for my delayed response, It is actually working in 5.6 and it's my fault why I encountered that issue. 

I am currently working on different projects that uses different versions of PHP - while developing I must have updated my php 5.6 composer while on php 7 because of that I got the abstract error. Sorry for that. Thanks.
